[package]
name = "amr-os"
authors = ["AbdooOwd"]
version = "0.1.0"
edition = "2024"

[[bin]]
name = "amr-os"
test = false
bench = false

[dependencies]
bootloader = "0.9"
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
spin = "0.10.0"
volatile = "0.2.6"
